Rahul/moving around the file system
uclaacm/linux-lab pull request #35
Opened 2022-07-02 15:53 UTC by r-mallick

## Summary

Closes #<set up Moving Around the File System page>

Transferred content from the content doc to moving.tsx and formatted accordingly. Did not do too much in terms of styling as figma mockup does not match with current content. 

## Test Plan

I periodically saved my material and ran yarn start to ensure that my content appears on the website as I intended.

2022-07-23 19:53 UTC, archishadatta requested changes

2022-07-23 19:53 UTC, archishadatta commented on src/components/pages/moving.tsx
> +//CSS styling
Looks great! Other people are working on the text styling, so you can remove this CSS and also where you used them.

2022-07-28 03:09 UTC, archishadatta submitted a review, later dismissed

2022-08-04 04:20 UTC, zhangjuliet approved these changes

2022-08-04 04:22 UTC, merged