feat: nav buttons setup
uclaacm/linux-lab pull request #38
Opened 2022-07-07 06:41 UTC by r-mallick

## Summary

Closes #29

Added navigation buttons that transition from page to page as per the mockup. I also added a hover feature that changes to a gray shade for looks. 

## Test Plan

Every time I added a set of next and previous buttons on one page, I ran yarn start. I made sure that the buttons linked to the proper pages and adjusted accordingly. I also ran yarn-lint to make sure no issues came up on that end.

2022-07-23 19:48 UTC, archishadatta requested changes

2022-07-23 19:48 UTC, archishadatta commented on src/styles/creation.scss
> +.lesson-title {
Other people are working on text styling, so remove any styles that do not have to do with the button

2022-07-23 19:48 UTC, archishadatta commented on src/styles/creation.scss
> +.back-button {
You don't need to put button styling in every scss page, you can put it in the global page. It will be applied across the entire project.

2022-07-23 19:55 UTC, zhangjuliet commented
Hard coding the buttons works for now and what you've done so far looks good, but in the future, if you work on Teach LA projects, you might want to do something more flexible for page navigation like this: https://github.com/uclaacm/boolbots/blob/main/src/components/shared/nextButton.tsx

2022-08-18 04:12 UTC, archishadatta approved these changes

2022-09-22 21:08 UTC, closed without merging